# Generated by Django 2.0.6 on 2018-07-05 06:25

import apps.v1.core.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.v1.core.model_utils.file_upload_to)),
                ('direct_link', models.URLField(blank=True, null=True)),
                ('document_format_type', models.CharField(choices=[('KING COUNTY', 'KING COUNTY')], default='KING COUNTY', max_length=255)),
                ('document_created_at', models.DateTimeField(blank=True, help_text='Date of  document creation date', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
